### ISSUE TITLE
vdev removal stalls out

### ISSUE THREAD

**Issue by ghost** [zfsonfreebsd/ZoF#100]
```sh
truncate -s 1g disk0 disk1
zpool create testpool disk0
zpool add testpool disk1
zpool remove testpool disk0
zpool status 1
```
The evacuation of disk0 slows to a crawl and fails to make appreciable progress. I did not find an open ticket for this upstream.

**Comment by ghost** [comment]
Actually that could be the test failures happening here:
http://build.zfsonlinux.org/known-issues.html (search for removal)

**Comment by allanjude** [comment]
Can you retest this with the updated repo?

**Comment by ghost** [comment]
It works now.
