### ISSUE TITLE
No instructions how to start

### ISSUE THREAD

**Issue by AndiDog** [zfsonfreebsd/ZoF#101]
The [ready for testing](https://www.freebsdnews.com/2019/01/10/zfs-on-freebsd-zof-is-ready-for-testing/) call links to https://zfsonfreebsd.github.io/ZoF/ which has an "Installation" heading that says

> Daily Snapshot Images are available from the TrueOS Project

That link gives a 404.

Some people might end up googling and finding the [mailing list call for testing](https://lists.freebsd.org/pipermail/freebsd-stable/2019-April/090915.html), which correctly links to the TrueOS download repository (sadly only x64 images, so people should still get information how to get the ports installed/configured on other platforms, if supported).

Can that please be described? At best, FreeBSD-related beta instructions should also be available at https://zfsonlinux.org/.

**Comment by kmoore134** [comment]
Just blasted the link to some social media, but here it is also for reference. I'll update the other page as well.

http://pkg.trueos.org/iso/freebsd-pkgbase/
