### ISSUE TITLE
Panic on casenorm tests

### ISSUE THREAD

**Issue by kmoore134** [zfsonfreebsd/ZoF#11]
While running the ZFS test suite, got a panic during the casenorm tests.

![zfs-panic1](https://user-images.githubusercontent.com/1933088/51194464-1a411500-18b9-11e9-939e-72aa35c55f89.png)
![zfs-panic2](https://user-images.githubusercontent.com/1933088/51194467-1c0ad880-18b9-11e9-8637-3d640aaa98da.png)

**Comment by mattmacy** [comment]
fixed by ec9ada1535f9b23d92154b8e03669a4dc45b6b3f
