### ISSUE TITLE
POLA violation: autotrim

### ISSUE THREAD

**Issue by rqqb** [zfsonfreebsd/ZoF#114]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	|  FreeBSD 13.0-CURRENT r349552
Distribution Version	| 
Linux Kernel	| 
Architecture	|  amd64
ZFS Version	|  openzfs-2019061900
SPL Version	| 

### Describe the problem you're observing

Legacy FreeBSD ZFS doesn't have the autotrim pool property, automatic trim is enabled by default.

Having autotrim default to `off' is a POLA violation.

**Comment by allanjude** [comment]
I think for this one we document it as a difference. I don't think having the default on FreeBSD different from the rest of OpenZFS is a good solution here.

**Comment by rqqb** [comment]
I'm OK with that, but it will need an entry in UPDATING when it's merged.

**Comment by allanjude** [comment]
For sure, We will need to make, announce, socialize, and really push a document with a list of important considerations when switching to the new version. I have a few even worse POLAs that I'd like to fix to get FreeBSD back in-line with upstream.

**Comment by mattmacy** [comment]
superseded by #150
