### ISSUE TITLE
Undefined symbol "zcmd_ioctl"

### ISSUE THREAD

**Issue by kmoore134** [zfsonfreebsd/ZoF#12]
While running this test:

https://github.com/zfsonfreebsd/ZoF/blob/projects/zfsbsd/tests/zfs-tests/tests/functional/channel_program/lua_core/tst.nvlist_to_lua.ksh

Getting the following error back:

ASSERTION: nvlist arguments can be passed to LUA.
ld-elf.so.1: /root/build/zfs/lib/libzfs_core/.libs/libzfs_core.so.1: Undefined symbol "zcmd_ioctl"                                                                                     
ERROR: nvlist_to_lua testpool exited 1

**Comment by mattmacy** [comment]
fixed by 2aaf1aa61fe85b53fc36b3e5175ae458568803ba
