### ISSUE TITLE
Attempt to mount Errata #3 filesystem deadlocks

### ISSUE THREAD

**Issue by ghost** [zfsonfreebsd/ZoF#125]
The zpool_import tests hit a deadlock in zpool_import_errata3 when attempting to mount an [errata 3](https://zfsonlinux.org/msg/ZFS-8000-ER/) filesystem.

The expected behavior is for the zfs mount command to fail and for read-only mount to succeed.

```
bzcat \
    tests/zfs-tests/tests/functional/cli_root/zpool_import/blockfiles/cryptv0.dat.bz2 \
    > /tmp/cryptv0.dat
zpool import -d /tmp/ cryptv0
# Notice errata is detected (displayed as Errata #4):
zpool status cryptv0
echo password | zfs load-key cryptv0/testfs
# This waits indefinitely on mntref instead of failing.
zfs mount cryptv0/testfs
```

**Comment by mattmacy** [comment]
Fixed in projects/pr-rebase-20191122,
