### ISSUE TITLE
How openzfs-kmod can be compiled as built-in kernel , like ZOL? not module.

### ISSUE THREAD

**Issue by javashin** [zfsonfreebsd/ZoF#130]
https://raw.githubusercontent.com/zfsonfreebsd/ZoF/projects/zfsbsd/copy-builtin works ?

**Comment by ghost** [comment]
Nope that doesn't work on FreeBSD, it's for Linux only.

We don't currently have a way to build this module in to the kernel as far as I'm aware, but that is something we should consider. I think what would be needed is a list of files needed for openzfs (a la sys/conf/files) and an appropriately customized kernel config.

**Comment by javashin** [comment]
Thanks for the clarification , i hope this get into the TODO list in some near future thanks.

**Comment by mattmacy** [comment]
@javashin it has to be support as part of downstreaming modern OpenZFS to FreeBSD HEAD. However, it's not really a priority until all other regressions have been dealt with.

**Comment by mattmacy** [comment]
@javashin https://github.com/mattmacy/networking/tree/projects/openzfs_vendor

**Comment by mattmacy** [comment]
@javashin https://reviews.freebsd.org/D25477

**Comment by javashin** [comment]
Amazing . I Will Try To Merge And Compile -Current With New Changes. Soon. and Comeback Here With Results.

**Comment by mattmacy** [comment]
It's still a WIP follow the mentioned branch

**Comment by javashin** [comment]
okey thx

**Comment by mattmacy** [comment]
@javashin Please follow this thread https://lists.freebsd.org/pipermail/freebsd-fs/2020-July/028355.html
