### ISSUE TITLE
Can't boot anything after r350387

### ISSUE THREAD

**Issue by rqqb** [zfsonfreebsd/ZoF#131]
### System information

FreeBSD | 13-CURRENT r350387
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 5
SPL Version	| 

### Describe the problem you're observing

mountroot fails 'File system not recognised"

### Describe how to reproduce the problem

Build/install e.g. r353029
with openzfs-2019061900

**Comment by ghost** [comment]
Your loader.conf should contain `openzfs_load=YES` as opposed to `zfs_load=YES`, can you verify that is the case?

**Comment by rqqb** [comment]
Yes.

**Comment by javashin** [comment]
compiled openzfs-kmod after compile the kernel rev r350387 ?

**Comment by javashin** [comment]
im beyond 353072    ...... .    there are 3000 commits after r350387 and there is new openzfs-kmod on ports

**Comment by javashin** [comment]
what kernel version my kernel ends on *48
checkout with uname -aK

**Comment by javashin** [comment]
Yes They Are Problems Again I cannot compile openzfs-kmod against -HEAD from today update

**Comment by rqqb** [comment]
Yes I didn't recompile openzfs-kmod before installing the new kernel, so that's the original issue.

I can't compile current openzfs-kmod against my current system.

**Comment by rqqb** [comment]
I'll see if I can revert openzfs-kmod to the version I have running.

**Comment by javashin** [comment]
/usr/ports/sysutils/openzfs-kmod/work/ZoF-27703da/module/os/freebsd/zfs/zfs_vnops.c:578:13: error: no member named
      'wire_count' in 'struct vm_page'; did you mean 'ref_count'?
                                if (pp->wire_count == 0 && pp->valid == 0 &&
                                        ^~~~~~~~~~
                                        ref_count
/usr/src/sys/vm/vm_page.h:213:8: note: 'ref_count' declared here
        u_int ref_count;                /* page references (A) */
              ^



this patch fixes this https://gist.githubusercontent.com/javashin/f60238463c20d5c67706a2a3f782b14b/raw/c60617e5cb3b00fd878dffd243b47b35a9c7f8b6/gistfile1.txt

**Comment by javashin** [comment]
`cat zfs_vnops.c.diff
--- work/ZoF-27703da/module/os/freebsd/zfs/zfs_vnops.c	2019-09-10 10:20:02.000000000 -0400
+++ ZoF-27703da.mod/module/os/freebsd/zfs/zfs_vnops.c	2019-10-04 07:08:51.095118000 -0400
@@ -575,14 +575,15 @@
 			vm_page_sunbusy(pp);
 			vm_page_lock(pp);
 			if (error) {
-				if (pp->wire_count == 0 && pp->valid == 0 &&
-				    !vm_page_busied(pp))
+				if (!vm_page_busied(pp) && !vm_page_wired(pp) &&
+				    pp->valid == 0)
 					vm_page_free(pp);
 			} else {
 				pp->valid = VM_PAGE_BITS_ALL;
+				vm_page_lock(pp);
 				vm_page_activate(pp);
+				vm_page_unlock(pp);
 			}
-			vm_page_unlock(pp);
 		} else {
 			ASSERT3U(pp->valid, ==, VM_PAGE_BITS_ALL);
 			vm_page_sunbusy(pp);
`

**Comment by javashin** [comment]
### --- work/ZoF-27703da/module/os/freebsd/zfs/zfs_vnops.c	2019-09-10 10:20:02.000000000 -0400
+++ ZoF-27703da.mod/module/os/freebsd/zfs/zfs_vnops.c	2019-10-04 07:08:51.095118000 -0400
@@ -575,14 +575,15 @@
 			vm_page_sunbusy(pp);
 			vm_page_lock(pp);
 			if (error) {
-				if (pp->wire_count == 0 && pp->valid == 0 &&
-				    !vm_page_busied(pp))
+				if (!vm_page_busied(pp) && !vm_page_wired(pp) &&
+				    pp->valid == 0)
 					vm_page_free(pp);
 			} else {
 				pp->valid = VM_PAGE_BITS_ALL;
+				vm_page_lock(pp);
 				vm_page_activate(pp);
+				vm_page_unlock(pp);
 			}
-			vm_page_unlock(pp);
 		} else {
 			ASSERT3U(pp->valid, ==, VM_PAGE_BITS_ALL);
 			vm_page_sunbusy(pp);

**Comment by javashin** [comment]
###  --- work/ZoF-27703da/module/os/freebsd/zfs/zfs_vnops.c	2019-09-10 10:20:02.000000000 -0400
+++ ZoF-27703da.mod/module/os/freebsd/zfs/zfs_vnops.c	2019-10-04 07:08:51.095118000 -0400
@@ -575,14 +575,15 @@
 			vm_page_sunbusy(pp);
 			vm_page_lock(pp);
 			if (error) {
-				if (pp->wire_count == 0 && pp->valid == 0 &&
-				    !vm_page_busied(pp))
+				if (!vm_page_busied(pp) && !vm_page_wired(pp) &&
+				    pp->valid == 0)
 					vm_page_free(pp);
 			} else {
 				pp->valid = VM_PAGE_BITS_ALL;
+				vm_page_lock(pp);
 				vm_page_activate(pp);
+				vm_page_unlock(pp);
 			}
-			vm_page_unlock(pp);
 		} else {
 			ASSERT3U(pp->valid, ==, VM_PAGE_BITS_ALL);
 			vm_page_sunbusy(pp);
  ###

**Comment by javashin** [comment]
testing now ...

**Comment by javashin** [comment]
Problem Solved uname -aK
FreeBSD hellbox-l440 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r353099M: Fri Oct  4 06:43:34 AST 2019     root@hellbox-l440:/usr/obj/usr/src/amd64.amd64/sys/DIABLO  amd64 1300048

boots and works faster because i fetched some @mattmacy  new fixes commits + the patch 
all fine

**Comment by javashin** [comment]
@rqqb compile/install new kernel and install this 2 packages with all the new commits and the patched kmod or patch the openzfs-kmod with gpatch -p1 -i ../patch  from the dir work/ZoF*****
after make extract and then make deinstall reinstall clean



[2-new-PKGS.zip](https://github.com/zfsonfreebsd/ZoF/files/3690371/2-new-PKGS.zip)

unzip inside they are 
2 *.txz that can be installed with pkg install

**Comment by rqqb** [comment]
That panicked, see:
![IMG_4727](https://user-images.githubusercontent.com/23299223/66235013-03607e00-e6e7-11e9-98a5-d0c174fb645b.JPG)

When I'm feeling stronger I'll boot off USB and see if I can roll back to my last good snapshot.

**Comment by javashin** [comment]
> That panicked, see:
> ![IMG_4727](https://user-images.githubusercontent.com/23299223/66235013-03607e00-e6e7-11e9-98a5-d0c174fb645b.JPG)
> 
> When I'm feeling stronger I'll boot off USB and see if I can roll back to my last good snapshot.

What Did You Do Installed The PKGS ? better try patching because all is working here , well i have some things different i do have clang 9 on base i think  you must have 8.0.1 i dont know if this can be an issue.

**Comment by ghost** [comment]
@javashin @rqqb Can either of you please test the latest commit on projects/zfsbsd and if that fixes things I'll have the port updated. Thanks in advance.

**Comment by javashin** [comment]
@freqlabs Im Rebuilding world because of new clang is going to be faster because i already have clang 9 in base i will compile everything openzfs related :) thanks

**Comment by javashin** [comment]
Everything works fine with new commits from master this can be closed .

**Comment by ghost** [comment]
Port has been bumped. Closing resolved.
