### ISSUE TITLE
devd events are not generated on FreeBSD

### ISSUE THREAD

**Issue by ghost** [zfsonfreebsd/ZoF#132]
We have compat code for sysevent interfaces such as `log_sysevent()` and `_ddi_log_sysevent()` from FreeBSD, but it is never invoked by ZoL. As a result, we do not get ZFS events through devd.

To observe:
```
cat /var/run/devd.seqpacket.pipe &
truncate -s 1G disk0
zpool create testpool `pwd`/disk0
zfs create testpool/testfs
zpool history testpool
zpool destroy testpool
kill $!
```
We can see the history is logged but devd is not generating events.

**Comment by darkfiberiru** [comment]
@freqlabs Is this still true?

**Comment by ghost** [comment]
Yes.

**Comment by darkfiberiru** [comment]
@pkgdemon I assume this will break some api tests  for 12 until fixed.
