### ISSUE TITLE
Reporting about pr-rebase-20191103 "Testing"

### ISSUE THREAD

**Issue by javashin** [zfsonfreebsd/ZoF#133]
### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	| 

### Include any warning/errors/backtraces from the system logs

I will leave that ^^^^ empty im just reporting :)_

i compiled today from https://github.com/zfsonfreebsd/ZoF/tree/d9e6557e28bcd4046fabed65d0119b60286b73de and my system is working better 

i got this 

sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!

But no other problem at all

zfs-utils and the kmod compiles fine with 

FreeBSD hellbox-l440 13.0-CURRENT FreeBSD 13.0-CURRENT #0 r354239M: Fri Nov  1 10:49:10 AST 2019     root@hellbox-l440:/usr/obj/usr/src/amd64.amd64/sys/DIABLO  amd64 1300054

so far all good , speed and stability are OK . i was having some hangs before and are gone

**Comment by ghost** [comment]
Thanks for the report.
