### ISSUE TITLE
Panic when trying to change key for a passphrase encrypted root dataset

### ISSUE THREAD

**Issue by sonicaj** [zfsonfreebsd/ZoF#134]
```
truenas# zpool create -O encryption=on -O keyformat=passphrase a /dev/da5
Enter passphrase:
Re-enter passphrase:
truenas# zfs create -o encryption=off a/nenc
truenas# zfs change-key a
Enter new passphrase for 'a':
Re-enter new passphrase for 'a':
```
Following the above steps results in a panic which causes a system reboot. I have been trying this on TN 12 latest

**Comment by mattmacy** [comment]
Works for me on projects/pr-rebase-20200107 - @freqlabs will update the port

**Comment by ghost** [comment]
Port was bumped for TN today. Should be running the latest commit in the next build.
