### ISSUE TITLE
Implement `seq_printf` shim in FreeBSD SPL

### ISSUE THREAD

**Issue by allanjude** [zfsonfreebsd/ZoF#137]
The following functions only exist in the linux version of the file, not the freebsd version:

spa_import_progress_show_header(struct seq_file *f)
spa_import_progress_show(struct seq_file *f, void *data)
spa_import_progress_truncate(spa_history_list_t *shl, unsigned int size)

Additionally, the following sysctls do not get created:

zfs_deadman_synctime_ms
spa_slop_shift

And possibly others

**Comment by mattmacy** [comment]
@allanjude  ` spa_slop_shift` isn't exported as a tunable by Linux either. Please enumerate the tunables you feel we need that they do not export.

**Comment by allanjude** [comment]
The two sysctl's mentioned are exported by legacy FreeBSD module

I think you renamed this issue by mistake.

**Comment by ghost** [comment]
I've implemented zfs_deadman_synctime_ms.

**Comment by mattmacy** [comment]
This adds support for procfs_list and a seq_printf shim
https://github.com/openzfs/zfs/pull/10890
