### ISSUE TITLE
setting userobjquota returns "invalid property value"

### ISSUE THREAD

**Issue by anodos325** [zfsonfreebsd/ZoF#139]
Enabled userobj accounting, but still unable to set userobjquotas on pool:

NAME   PROPERTY                    VALUE                       SOURCE
dozer  feature@userobj_accounting  enabled                     local

tn12test# zfs set userobjquota@smbuser=1000 dozer/SMB       
cannot set property for 'dozer/SMB': invalid property value

**Comment by mattmacy** [comment]
@freqlabs did you fix this with your quota consolidation?

**Comment by ghost** [comment]
Yep fixed.
