### ISSUE TITLE
libzfs missing zmount declaration

### ISSUE THREAD

**Issue by kevans91** [zfsonfreebsd/ZoF#141]
The implementation's already in libzfs, the declaration's just missing from the header: https://svnweb.freebsd.org/base/head/cddl/contrib/opensolaris/lib/libzfs/common/libzfs.h?view=markup#l865

We use this in base libbe.

**Comment by mattmacy** [comment]
@kevans91 zmount is FreeBSD specific - there's do_mount which we can give a more ZFS specific name declaring in libzfs_impl.h

If you'd like to change the name of that please submit a PR to ZoL
