### ISSUE TITLE
Panic during rsend tests

### ISSUE THREAD

**Issue by kmoore134** [zfsonfreebsd/ZoF#15]
During the rsend_013_pos test:

![panic1](https://user-images.githubusercontent.com/1933088/51277838-cb71a900-19a6-11e9-990d-b462ad1558a1.png)
![panic2](https://user-images.githubusercontent.com/1933088/51277842-cca2d600-19a6-11e9-9917-29a15894bc6c.png)
![panic3](https://user-images.githubusercontent.com/1933088/51277846-ce6c9980-19a6-11e9-81ee-f0af7f31af27.png)

**Comment by mattmacy** [comment]
fixed
