### ISSUE TITLE
atime fails

### ISSUE THREAD

**Issue by kmoore134** [zfsonfreebsd/ZoF#18]
The atime test suite is showing that atimes are not being updated on read, even though setting atime=on appears to pass:

SUCCESS: zfs set atime=on testpool/testfs
SUCCESS: cat /tests/testdir/testfile
ERROR: check_atime_updated /tests/testdir/testfile exited 1

Confirmed the test framework is doing the right thing during testing, and manually tried setting atime=on on a ZFS pool, which also confirmed times are not updated on read. 

Using:
```ls -luD "%Y-%m-%d %R.%s"``` to check the times.

**Comment by kpande** [comment]
does `mount` show it mounted with atime?

**Comment by kmoore134** [comment]
This was already fixed in a commit yesterday, and yes it was mounted with atime ;)

**Comment by kmoore134** [comment]
For reference, here's the commit in question: 7f0929432188b888c8714f5143517bc362b5d16e
