### ISSUE TITLE
Broken groupquota

### ISSUE THREAD

**Issue by kmoore134** [zfsonfreebsd/ZoF#23]
Various groupquota tests are failing, while userquota tests appear to pass. Looks like the groupquotas are being set properly, but then not enforced, while user quotas are. 

SUCCESS: rm -f /tests/testdir/qf
NOTE: Check the groupquota@qgroup
SUCCESS: zfs set groupquota@qgroup=4000000 testpool/testfs
SUCCESS: chmod 0777 /tests/testdir
NOTE: user:quser1 mkfile 4000000 /tests/testdir/qf
SUCCESS: user_run quser1 mkfile 4000000 /tests/testdir/qf
SUCCESS: zpool sync testpool
NOTE: user:quser1 mkfile 1 /tests/testdir/of
ERROR: user_run quser1 mkfile 1 /tests/testdir/of unexpectedly exited 0

**Comment by mattmacy** [comment]
@freqlabs still an issue?

**Comment by ghost** [comment]
This was due to group owner being inherited from the containing dir on FreeBSD rather than being the eguid of the creating user. It's been fixed and the tests have been reenabled.
