### ISSUE TITLE
zinject: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#24]
Zinject seems broken on ZoF. In addition to expect output, when calling 'zinject' an error occurs with:
`Unable to list handlers: Inappropriate ioctl for device`

When calling 'zinject -a', a similar error occurs:
`failed to add handler: Inappropriate ioctl for device`

This affects a few tests, namely deadman, fault, and removal. These fail on 'zinject -c' and 'zinject -d' too. This seems related to the ioctl syscall in the zinject c file. See also "dd: Inappropriate ioctl for device", when running devices/devices_001.

**Comment by kmoore134** [comment]
Matt - Confirmed this here, causes a bunch of tests to fail:

```
failed to add handler: Inappropriate ioctl for device
ERROR: zinject -d /tests/file-1 -e io -T read testpool exited 1
```

**Comment by ZackaryWelch** [comment]
Reproduction script:
```
#!/bin/ksh

#Setup
ROOT=/root/build/zfs/bin #Needed on my system
truncate -s 10G md0
truncate -s 10G md1
if [[ -z `ls /dev | grep md0` ]]; then
        sudo mdconfig -a -t vnode -f md0
fi
if [[ -z `ls /dev | grep md1` ]]; then
        sudo mdconfig -a -t vnode -f md1
fi
sudo $ROOT/zpool create -f testpool /dev/md0 /dev/md1
rm -rf /var/tmp/testdir
mkdir -p /var/tmp/testdir
sudo $ROOT/zfs create testpool/testfs
sudo $ROOT/zfs set mountpoint=/var/tmp/testdir testpool/testfs

#Devices_001
sudo $ROOT/zfs set devices=on testpool/testfs
sudo mknod /var/tmp/testdir/testfile1 b 0 75
dd if=/var/tmp/testdir/testfile1 of=/var/tmp/testdir/testfile1.out count=1
sudo mknod /var/tmp/testdir/testfile2 c 13 2
dd if=/var/tmp/testdir/testfile2 of=/var/tmp/testdir/testfile2.out count=1

#Cleanup
sudo umount -a
sudo $ROOT/zpool destroy -f testpool
sudo mount -a
```
Should return:
``dd: /var/tmp/testdir/testfile1: Inappropriate ioctl for device``

``dd: /var/tmp/testdir/testfile2: Inappropriate ioctl for device``

**Comment by ZackaryWelch** [comment]
For fault tests that aren't skipped (auto_spare_001, auto_spare_002, auto_spare_multiple, decrypt_fault, decompress_fault), they all fail on a `zinject` command. Kris commented the one that fails auto_spare_001.

**Comment by mattmacy** [comment]
fixed by 7f4f6a9638be003188d0ae62b12a3d197cbc84d3

**Comment by ZackaryWelch** [comment]
Devices_001 still fails

**Comment by ZackaryWelch** [comment]
Maybe should be a separate issue, since 'zinject' now works, though 'dd' fails.

**Comment by mattmacy** [comment]
@ZackaryWelch does this test pass on legacy ZFS? I'm not convinced that one can mknod like that with devfs

**Comment by mattmacy** [comment]
?

**Comment by ZackaryWelch** [comment]
Doesn't pass on legacy ZFS. Should devices_001 be skipped then on FreeBSD?

**Comment by kmoore134** [comment]
Yep, go ahead and skip it if it doesn't work on legacy either.
