### ISSUE TITLE
Converting or disabling tests which make use of extended file attributes

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#27]
A few test fail due to commands such as 'lsattr', 'attr', 'setfattr', and 'xattr'. These are:
features/large_dnode_002, large_dnode_006, large_dnode_008, rsend/send_encrypted_files, send_realloc_dnode_size, and upgrade/upgrade_projectquota_001. The latter has been set to skipped for other reasons. These either need to be converted to another system to work in FreeBSD or disabled due to not supporting the Linux feature. The script cmd/xattrtest fails to build due to lack of <sys/xattr.h>, which is used by some tests.

**Comment by kmoore134** [comment]
@ZackaryWelch go ahead and disable those tests for FreeBSD. Not expected to work at this time.

**Comment by ZackaryWelch** [comment]
Seems I already did that, so I'll close this.
https://github.com/zfsonfreebsd/ZoF/commit/de161cddf653e92f4ab8b5efc16fee60bcdf52e2
