### ISSUE TITLE
'zpool import -d' fails in history tests

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#28]
In two tests (history_001 and history_007), the uncompress command fails:
```
uncompress: /tests/import_dir.19634/zfs-pool-v4.dat.Z already has .Z suffix -- unchanged
ERROR: uncompress /tests/import_dir.19634/zfs-pool-v4.dat.Z exited 1
```
I have been unable to reproduce this error normally.

**Comment by ZackaryWelch** [comment]
https://github.com/zfsonfreebsd/ZoF/commit/4c85b686ddfd0f4196f0b4f17dcd3d413b6e9e7a
Fixed the uncompress issue with a '-f' flag. Now I get an error in history_001:
```
ERROR: zpool import -d /tests/import_dir.24056 exited 1
```
This is due to the full segment being:
```
upgrade_pool=$(zpool import -d $import_dir | grep "pool:" | awk '{print $2}')
log_must zpool import -d $import_dir $upgrade_pool
```
And the $upgrade_pool variable is empty when running 'zpool import'. This seems to be due to 'zpool import' not returning any output.
For history_007, the error is:
```
cannot import 'history_pool': no such pool available                                         
ERROR: zpool import -d /tests/testdir/importdir.46356 history_pool exited 1 
```
Which results from the pool being destroyed beforehand to insure the import command succeeds. These seem to be issues with the 'zpool import' command.

**Comment by kmoore134** [comment]
Appears related to #70 , but the -d <dir> flag isn't working and causes zpool import to fail.

**Comment by mattmacy** [comment]
@freqlabs please provide a standalone repro

**Comment by ghost** [comment]
The problem here is with the test itself. When it calls `uncompress` the utility is actually compressing the file:
```
SUCCESS: mkdir /var/tmp/import_dir.76468
SUCCESS: cp /home/ryan/ZoF/tests/zfs-tests/tests/functional/history/zfs-pool-v4.dat.Z /var/tmp/import_dir.76468
SUCCESS: uncompress -f /var/tmp/import_dir.76468/zfs-pool-v4.dat.Z
NOTE: upgrade_pool: 
NOTE: import_dir contents: zfs-pool-v4.dat.Z.gz
NOTE: import: 
ERROR: zpool import -d /var/tmp/import_dir.76468 exited 1
```
I should be able to figure this out.

**Comment by ghost** [comment]
"There's your problem"
```
ryan@zof-vm:~/ZoF % ll bin/uncompress 
lrwxr-xr-x  1 ryan  ryan  25 Jun 21 16:24 bin/uncompress@ -> /home/ryan/ZoF/bin/gunzip
```
