### ISSUE TITLE
Ztest requires that linprocfs be mounted

### ISSUE THREAD

**Issue by mattmacy** [zfsonfreebsd/ZoF#3]
`getprogname()` needs to be used instead

### System information

Type | Version/Name
 --- | --- 
Distribution Name	| 
Distribution Version	| 
Linux Kernel	| 
Architecture	| 
ZFS Version	| 
SPL Version	|

**Comment by kpande** [comment]
seems like this project also needs freebsd-specific issue template. Linux kernel seems unnecessary here?

**Comment by ryao** [comment]
`getprogname()` appears to be available on FreeBSD, OpenBSD and Illumos. It seems to be the correct API function for this but we do not have it on any Linux libc from what I can tell. If it is not too much trouble, it would be nice if an autotools check were written with a small shim implementing `getprogname()` via linprocfs when getprogname() is not found. That way, the code would be both cleaner and more portable. If a Linux libc ever implements this, then the autotools check should gracefully switch to using it.

**Comment by ryao** [comment]
I have a minor correction. It appears that Android Linux’s bionic libc implements `getprogname()`

https://android.googlesource.com/platform/bionic/+/master/libc/upstream-openbsd/lib/libc/gen/getprogname.c

The other libcs for Linux reportedly do not:

https://patchwork.ozlabs.org/comment/1543656/

**Comment by mattmacy** [comment]
fixed
