### ISSUE TITLE
Known issue with rsend and hanging

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#30]
Some rsend test have issues known in zfsonlinux/zfs, in particular rsend_019, rsend_020, rsend_021, and rsend_024. With these rsend_020, rsend_021, rsend_024, and rsend_022, all have a tendency to hang and need to be killed by the process. This might be a machine issue, but I've disabled these tests on FreeBSD for the moment since they fail.

**Comment by mattmacy** [comment]
rsend_{019, 020, 021} pass 022 and 024 fail

**Comment by mattmacy** [comment]
Fixed with recent changes.
