### ISSUE TITLE
Operation not supported for mkdir and mv in snapshot tests

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#33]
In snapshot, snapshot_015 and snapshot_016 fail due to basic system commands not being able to execute. In snapshot_015, mkdir fails to create a directory /tests/testdir/.zfs/snapshot/snap.0. Full error:
```
mkdir: /tests/testdir/.zfs: Operation not supported
ERROR: mkdir -p /tests/testdir/.zfs/snapshot/snap.0 exited 1
```
Switching to -p makes the operation work outside the test, but does not change the error.
In snapshot_016, mv fails to rename a directory:
```
mv: rename /tests/testdir/.zfs/snapshot/testsnap to /tests/testdir/.zfs/snapshot/snap_a: Operation not supported
ERROR: mv /tests/testdir/.zfs/snapshot/testsnap /tests/testdir/.zfs/snapshot/snap_a exited 1
```

**Comment by ghost** [comment]
FreeBSD does not support this method of creating snapshots. These tests have to be disabled on FreeBSD.
