### ISSUE TITLE
Snapshot/clone_001 fails due to known issue

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#36]
Snapshot/clone_001 failing is considered expected due to a known issue, however the test is not skipped on FreeBSD. The error is:
```
cannot create 'testpool1': no such pool or dataset
ERROR: zpool create -f testpool1 /dev/zvol/testpool/testvol exited 1
```
And occurs during the setup of the test.

**Comment by ZackaryWelch** [comment]
The error occurs in create_pool in libtest.shlib. Unsure why this issue is occuring, and it might be related to other issues with /dev/zvol/testpool/testvol.

**Comment by ghost** [comment]
This was due to zvol recursion. Fixed to allow recursive pools.
