### ISSUE TITLE
Truncate succeeds unexpectedly in large_files_002

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#37]
The test large_files/large_files_002 fails due to truncate succeeding through a  'ulimit -f 1024'. The full error is:
```
ERROR: sh -c truncate -s2M $TESTDIR/ulimit_trunc_file unexpectedly exited 0
```
And occurs in the segment:
```
# Verify 'ulimit -f unlimited' works
log_must ulimit -f unlimited
log_must sh -c 'dd if=/dev/zero of=$TESTDIR/ulimit_write_file bs=1M count=2'
log_must sh -c 'truncate -s2M $TESTDIR/ulimit_trunc_file'
log_must rm $TESTDIR/ulimit_write_file $TESTDIR/ulimit_trunc_file
```

**Comment by ZackaryWelch** [comment]
Seems less of an error with 'truncate' and more with 'ulimit'. Also I can replicate this outside of the test. Maybe FreeBSD has a different way of doing this? 'limit' and 'ulimit' both seem to fail though.

**Comment by Godwottery** [comment]
Looks like it should be a change of command: 
From ```man limits```: 
```-f	[val]  Select or set the filesize resource limit.```
https://www.freebsd.org/cgi/man.cgi?query=limits&section=1

From ```man ulimit```:
```-f   The maximum size of files created by the shell(default option) ```
https://ss64.com/bash/ulimit.html

I would guess that changing the line to read ``` log_must limits -f unlimited``` should work.
It might even be that ulimit is a bash-specific command.

**Comment by ghost** [comment]
The tests use ksh93, and ulimit is a builtin command.
https://linux.die.net/man/1/ksh93

**Comment by mattmacy** [comment]
Not a kmod issue

**Comment by ghost** [comment]
Fixed.
