### ISSUE TITLE
Quota_001 through quota_004 fail due to disc quota exceeded

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#40]
In quota_001, quota_002, quota_003, and quota_004, the same error:
```
write failed (-1), good_writes = 1217, error: Disc quota exceeded[69]
Returned error code: 69. Expected: 49.
```
occurs when calling 'file_write' to the write_size determined by the quota.

**Comment by ZackaryWelch** [comment]
In quota.kshlib, there is a line:
```
if is_linux; then
        readonly EDQUOT=122
else
        readonly EDQUOT=49
fi
```
I could add a line for is_freebsd where EDQUOT=69. Does that sound right?

**Comment by kmoore134** [comment]
@ZackaryWelch That sounds like the correct action. Go ahead and do an
`
elif is_freebsd ; then

  readonly EDQUOT=69
else
`

**Comment by ZackaryWelch** [comment]
Okay, done and the tests pass now. That was quick!
https://github.com/zfsonfreebsd/ZoF/commit/75a6c8ff66a6d284d3fea2e1ee8a4aa6efbf5fa2
