### ISSUE TITLE
mmp/setup fail due to lack of zfs_multihost_history in FreeBSD

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#42]
Initally, when the mmp/setup test will fail due to an existing hostid file, as seen in:
```
if [ -e $HOSTID_FILE ]; then
        log_unsupported "System has existing $HOSTID_FILE file"
fi
```
If this file is deleted or break skipped, then the test will fail at the next line:
```
log_must set_tunable64 zfs_multihost_history $MMP_HISTORY
```
When adding zfs_multihost_history to freebsd_sysctl.c, the build will fail because the variable is missing from spa_stats.c, unlike on linux.
First, should the hostid file be removed on FreeBSD first? What should be done with that error.
Secondly, it seems spa_stats.c will need to be completed before this test could complete, since it is currently empty save for only function definitions.

Edit:
See cli_root/zpool_split/zpool_split_props for a similar error with existing hostid

**Comment by ZackaryWelch** [comment]
The HostID part seems like it can be fixed easily, but zfs_multihost_history is part of spa_stats. This should probably be two separate issues, one of hostid errors and another for tests that fail with spa_stats.

**Comment by mattmacy** [comment]
reassign when you've fixed the non-kmod issues

**Comment by ghost** [comment]
The mmp tests should handle an existing hostid file now.

**Comment by ghost** [comment]
Skipping mmp tests for now.
