### ISSUE TITLE
link_count/link_count_001 fails due to multithreading issues

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#43]
The link_count test fails as the C script is unable to exit properly. It seems in rm_linkcnt_zero_file.c, the condition to exit is never reached, as s.st_nlink must not be 1 or 2. This could be due to how the vm is configured as well.

**Comment by ZackaryWelch** [comment]
Maybe my vm needs more cores/threads to test this fully, but it seems like an issue in zfs, since the test works, it just fails.

**Comment by ghost** [comment]
Mav says this should not be a concern for us.
