### ISSUE TITLE
dd fails into clone, as well as for renames

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#44]
In nopwrite/sync, the test fails with the error:
```
dd into /tests/testdir/file failed.
```
on the line:
```
dd if=/dev/urandom of=$TESTDIR/file bs=1024k count=$MEGS oflag=sync \
    conv=notrunc >/dev/null 2>&1 || log_fail "dd into $TESTDIR/file failed."
```
Nopwrite/volume also fails, but only occasionally, with a similar error:
```
dd into testpool/clone failed.
```
on:
```
dd if=$vol of=$volclone bs=8192 count=4096 conv=notrunc >/dev/null 2>&1 || \
    log_fail "dd into $clone failed."
```
Edit:
See also cli_root/zfs_rename/zfs_rename_002 and cli_root/zfs_rename/zfs_rename_007. The log for 002 is shown below:
```
ERROR: eval dd if=/dev/zvol/testpool/testvol of=/tests/testdir2/voldata.rename bs=512 count=2048 >/dev/null 2>&1 exited 1
```

**Comment by ZackaryWelch** [comment]
The zfs_rename tests might be related to https://github.com/zfsonfreebsd/ZoF/issues/68

**Comment by ZackaryWelch** [comment]
https://github.com/zfsonfreebsd/ZoF/commit/97312533dfc73a05c36e77d3020b7c3c2fff2e26
Disabled nopwrite_sync because flags are not supported on FreeBSD. For nopwrite_volume, the error is currently:
```
dd: /dev/zvol/testpool/clone: Operation not supported
```
Unsure why this is the case, since the initial dd works. This would also make it related to the zfs_rename issues. More debugging needs to be done on the zfs_rename tests too.

**Comment by allanjude** [comment]
this test still needs to be addressed

**Comment by ghost** [comment]
I've resolved the nopwrite tests, rename still needs to be looked at.

**Comment by ghost** [comment]
rename 007 passes, rename 002 still failing with the message `Send filesystem must not exist.`

**Comment by ghost** [comment]
The dd issues are fixed though.
