### ISSUE TITLE
Rootpool_007 fails, unable to detect pool

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#45]
The test rootpool/rootpool_007 fails with the error:
```
ERROR: zfs set compression=gzip NOTE: Pool This not exists. exited 1 
```
The NOTE is generated from the variable $rootfs which runs 'get_pool_prop bootfs $rootpool', however the rootpool found with get_rootpool cannot be verified to exist with 'poolexists'.

**Comment by ZackaryWelch** [comment]
Marking this as later since it is disabled by default and might be due to the structure of my vm. Testing this has proven difficult, and I'm quite sure it won't work on my system anyway. The main issue is that it gets the pool name from an echo, and log_note also gives output to stdout, which affects the test.

**Comment by ghost** [comment]
Should be working after recent improvements, but untested on an actual root pool.
