### ISSUE TITLE
Change from procfs in cli_root/zfs_mount/zfs_mount_remount

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#48]
The function currently looks at /proc/mount in the line:
`options="$(awk -v ds="$dataset" '$1 == ds { print $4 }' /proc/mounts)"`
in order to check if a filesystem is read/writeable or not. I currently changed the line to look at /etc/fstab, but the test probably will not work. If this tests still fails, this line will need to be written further and possibly use a different means, such as sysctls or mount command.

**Comment by ZackaryWelch** [comment]
Since /etc/fstab only concerns boot and isn't modified by the tests, that's not a valid option. There doesn't seem to be any related sysctls, and the mount command does not how i/o options. Therefore, I disabled the options check on FreeBSD and only check to see if the dataset is mounted and assume that the options were set correctly by touch for 'rw' and file_write for 'ro'.

**Comment by ZackaryWelch** [comment]
https://github.com/zfsonfreebsd/ZoF/commit/9ab68fe7784e1622459713a7709b5888a576f5e9
The 'remount' option is also not supported on FreeBSD, so I removed that option from all mount commands on FreeBSD. Unsure if that breaks the test, since it is trying to test remounting. Should the test be skipped since both remount and checking current rw/ro options is not supported? I don't know if the remount behavior doesn't exit or just the option. Currently the test still fails for some reason unknown, so I'll disable the test for now and leave up the issue.
Current error:
```
SUCCESS: touch /testpool/testfs/file.dat
NOTE: Dataset testpool/testfs is mounted
mount: testpool/testfs: No such file or directory
ERROR: mount -o ro testpool/testfs /testpool/testfs exited 1
```

**Comment by ghost** [comment]
Fixed by adapting the arguments to mount for FreeBSD.
