### ISSUE TITLE
Invalid argument in 'zfs program' command on cli_root/zfs_program

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#49]
The test zfs_program/zfs_program_json fails due to the cli unable to parse a '-j' argument in 'zfs program'. The full error is:
```
cannot open '-j': No such file or directory
ERROR: zfs program testpool -j /testpool/zcp-json/zfs_rlist.zcp testpool/zcp-json recordsize exited 1
```

**Comment by ghost** [comment]
Fixed by 3864ef066e1c2abe1eee850f622b6d13aeeda40f on projects/pr-rebase
