### ISSUE TITLE
Cli_root/zpool/ enable coredumps by switching from procfs or coreadm to a FreeBSD version

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#50]
Currently the test runs:
```
if is_linux; then
        ulimit -c unlimited
        echo "$corepath/core.zpool" >/proc/sys/kernel/core_pattern
        echo 0 >/proc/sys/kernel/core_uses_pid
        export ASAN_OPTIONS="abort_on_error=1:disable_coredump=0"
else
        coreadm -p ${corepath}/core.%f
fi
```
Coreadm does not exist on FreeBSD, but the Linux section doesn't work either. I'm unsure how this is supposed to work on FreeBSD, or what it even does. The test fails later with:
```
zpool create pool.22604 mirror /tests/testdir/file1 /tests/testdir/file2 cannot generate core file with ZFS_ABORT set.
```

That same codeblock is also run on zpool_003, which fails due to:
```
zpool did not dump core by request.
```

**Comment by ZackaryWelch** [comment]
I'll see if the procfs commands could be replaced with sysctls, but I'm not entirely sure whch ones correspond.

**Comment by ZackaryWelch** [comment]
Currently testing not using /proc/sys/kernel/core_uses_pid and changing /proc/sys/kernel/core_pattern to kern.corefile. This might end up being a zfs issue too.

**Comment by ZackaryWelch** [comment]
https://github.com/zfsonfreebsd/ZoF/commit/5eb00e2b24ce1b75dd59505507d8a8f8399a3631
Currently the segment for FreeBSD looks like:
```
        ulimit -c unlimited
        log_must /sbin/sysctl kern.corefile=$corepath/core.zpoool
        export ASAN_OPTIONS="abort_on_error=1:disable_coredump=0"
```
But it doesn't work. I'm unsure about all three lines: if ulimit works, as there's another issue involving ulimit, and if ASAN_OPTIONS and ZFS_ABORT work properly. Even if all of those do work, the sysctl might not do anything. There doesn't seem to be another I could use. @mattmacy could you verify there isn't an issue with ASAN_OPTIONS and ZFS_ABORT? I think the sysctl is configured correctly.

**Comment by mattmacy** [comment]
This looks like a scripting issue

**Comment by ghost** [comment]
Fixed.
