### ISSUE TITLE
'zpool attach'  and 'zpool replace' command succeeds with ashift

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#51]
The test cli_root/zpool_attach/attach-o_ashift fails with the error:
```
zpool attach -o ashift=10 testpool1 /tests/filedisk0_create /tests/filedisk1_create unexpectedly exited 0
```
A similar error occurs in zpool_replace/replace-o_ashift and replace_prop_ashift
```
ERROR: zpool replace -o ashift=10 testpool1 /tests/filedisk0_create /tests/filedisk1_create unexpectedly exited 0
```
and
```
ERROR: zpool replace testpool1 /tests/filedisk0_create /tests/filedisk1_create unexpectedly exited 0
```

**Comment by allanjude** [comment]
How are we handling ashift?

The freebsd way, the ZoL way, or both? (fall back to freebsd sysctl is not specified on the command line)?

Additionally, this issue does not appear to be resolved yet

**Comment by mattmacy** [comment]
To start with the Linux way

**Comment by ghost** [comment]
Passes on 20200107
