### ISSUE TITLE
'zpool status -P -c iostat testpool' command fails

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#54]
In cli_root/zpool_status/zpool_status_003_pos, the test_zpool_script function fails due to:
```
'zpool status -P -c iostat testpool' created no new columns 
```
This succeeds for other values before iostat. The complete list of statuses checked with the test can be found in /usr/local/etc/zfs/zpool.d, where the test starts with ata_err and fails at iostat.
Edit:
The same error occurs in cli_user/zpool_iostat/zpool_iostat_005

**Comment by allanjude** [comment]
This needs to be addressed

**Comment by mattmacy** [comment]
`zpool.d/iostat` needed to be adapted for FreeBSD and Linux
