### ISSUE TITLE
cli_root/zpool_get_002 fails to find all features

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#55]
The test cli_root/zpool_get/zpool_get_002 runs through 53 properties found with 'zpool get all testpool' and finds them all, but there seems to be a missmatch with the values in properties and those found with the 'zpool get', since at the end only 46 can be found.
Full error:
```
Found zpool features not in the zpool_get test config 46/53.
```

**Comment by ghost** [comment]
Fixed the test config to check for the additional features Linux has on FreeBSD as well.
