### ISSUE TITLE
Python tests in cli_user/misc fail to read from /proc

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#61]
Five tests in cli_user/misc run four python scripts:
arc_summary_001 and arc_summary_002, which runs arc_summary.py
arc_summary3 runs arc_summary3.py
arcstat_001 runs arcstat.py
dbufstat_001 runs dbufstat.py
All of these tests fail with an error such as:
```
ERROR: eval python3 /usr/local/bin/arc_summary3.py > /dev/null exited 1
```
If a traceback is given, the error will look like, as in arc_summary3:
```
Traceback (most recent call last): File "/usr/local/bin/arc_summary3.py", line 875, in <module> main() File "/usr/local/bin/arc_summary3.py", line 826, in main kstats = get_kstats() File "/usr/local/bin/arc_summary3.py", line 259, in get_kstats with open(PROC_PATH+section, 'r') as proc_location: FileNotFoundError: [Errno 2] No such file or directory: '/proc/spl/kstat/zfs/arcstats'
```

It seems these python files will need to be modified to get the stats in a manner outside of /proc, perhaps with sysctls.

**Comment by ZackaryWelch** [comment]
arc_summary, arc_summary3, and arcstat have all been updating and work on FreeBSD, with the added dependency of py-sysctl. Debufstat has been disabled because it relies too heavily on procfs. All of these do the same thing basically, but dbufstat uses file io throughout the entire program, requiring more of a rewrite. Disabling it should be fine for now, but it could be fixed by a rewrite using py-sysctl.

**Comment by ZackaryWelch** [comment]
https://github.com/zfsonfreebsd/ZoF/commit/7df774caf4c2280c3f1ff920b294c65417ac0594
https://github.com/zfsonfreebsd/ZoF/commit/3b298e6c5632597f4f0ad84b368ea44b96209daf
https://github.com/zfsonfreebsd/ZoF/commit/36bf492ce4bb14847e7a889c5fa183a47f7287b9

**Comment by ghost** [comment]
Python utils have been updated to not use procfs and sysfs on FreeBSD except dbufstat, for which we currently skip tests.
