### ISSUE TITLE
Failure to set property for pool in cli_root/zfs_set/checksum_001

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#62]
The test cli_root/zfs_set/checksum_001 fails with the error:
```
cannot set property for 'testpool': pool and or dataset must be upgraded to set this property or value
ERROR: zfs set checksum=edonr testpool exited 1
```
The tests succeeds for other properties. This seems to be an issue with 'checksum=edonr'.

**Comment by ghost** [comment]
edonr is not supported on FreeBSD
