### ISSUE TITLE
Issues converting from Linux mount in cli_root/zfs_set/mountpoint_003

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#63]
The test cli_root/zfs_set/mountpoint_003 fails with the error:
```
mount: testpool/testfs: mount option <devices> is unknown: Invalid argument
ERROR: mount -F zfs -o devices testpool/testfs /tmpmnt.31955 exited 1
```
It seems the option 'devices' does not exist on FreeBSD, but I cannot find documentation for the option on Linux either.

**Comment by ZackaryWelch** [comment]
https://github.com/zfsonfreebsd/ZoF/commit/fb708c54283b3118db35fff5ca8f7996b5aea17f
https://github.com/zfsonfreebsd/ZoF/commit/4f4c5af7f7529628de012ae7d1c3b32c0ca9bc59

**Comment by ZackaryWelch** [comment]
Now I get an error:
```
Expected option: nodev \n Real option: testpool/testfs on /tmpmnt.56581 (zfs, local, noatime, nosuid, nfsv4acls)
```
This might actually be an issue with zfs, or that nodev is not supported on FreeBSD.

**Comment by ZackaryWelch** [comment]
Question about the mount options. I should have a list of all options for FreeBSD. I'm a little confused though, because the man page only lists non-default options, so I see 'noexec' and 'noatime', but am I to assume 'exec' and 'atime' are also valid options? It's also stupid that if you give mount junk for an option, it won't return an error.

**Comment by ZackaryWelch** [comment]
Currently I have 'exec', 'noexec', 'ro', 'rw', 'nosuid', 'suid', 'atime' and 'noatime'. Basically leaving out 'nodev', 'dev', 'xattr', and 'noxattr' from Linux, but I feel I'm missing a few. Should I just leave it at those 8 (4)?

**Comment by kmoore134** [comment]
I'd leave it at those 8 for now. I think those cover the bulk of important ones.

**Comment by ZackaryWelch** [comment]
https://github.com/zfsonfreebsd/ZoF/commit/12afe54ade26c6f363fd2684ad5678262cc04282
Now passes. I'll close this issue then, though I have a comment saying that more might be added in the future.
