### ISSUE TITLE
Multiple cli_root/zfs_mount tests fail in suceeding to mount

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#65]
Tests in cli_root/zfs_mount, namely zfs_mount_005, 006, 007, 008, 010, and 012 all give an error when attempting to fail a 'zfs mount' command. The errors all look like:
```
NOTE: Verify that 'zfs mount <filesystem>' with a mountpoint that is identical to an existing one will fail with return code 1.
SUCCESS: zfs set mountpoint=/tests/testdir/0/1/2 testpool/testfs1
NOTE: zfs mount testpool/testfs1
-u2
ERROR: zfs mount testpool/testfs1 unexpectedly exited 0
```

**Comment by ghost** [comment]
Tests adapted to check for the correct platform-specific behavior (or skip in the case of 6/7/8 on FreeBSD).
