### ISSUE TITLE
'zfs create -o sharenfs=ON' succeeds in cli_root/zfs_create/zfs_create_008

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#67]
In the test cli_root/zfs_create/zfs_create_008, a variety of failing 'zfs create' commands are tried, with the test throwing an error when the following succeeds:
```
SUCCESS: zfs create -p -o mountpoint=LEGACY testpool/testfs1 exited 1
SUCCESS: zfs create -o mounpoint=none testpool/testfs1 exited 1
SUCCESS: zfs create -p -o mounpoint=none testpool/testfs1 exited 1
-u2
ERROR: zfs create -o sharenfs=ON testpool/testfs1 unexpectedly exited 0
```

**Comment by ghost** [comment]
This is because our zfs_init_libshare_impl() and friends are only dummies.

**Comment by ghost** [comment]
Tests have been updated to skip sharenfs testing on FreeBSD for now.
