### ISSUE TITLE
Kernel panic when installing when loading using bhyve

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#7]
I am using TrueOS built with ZoF running with bhyve. I gave the vm 16GB of hard disk space and 1024MB of memory. Changing the memory to 4GB did not prevent this issue. When I installed TrueOS onto a vm image in bios, the installation finished successfully, but when loading the image afterwards I see:

> Consoles: userboot  
>
> FreeBSD/amd64 User boot lua, Revision 1.2
> panic: free: guard2 fail @ 0x8447f8620 + 2065 from unknown:0

I tried installing multiple times but I get the same error each time. I also tried installing in uefi to no avail.
The image I used is TrueOS-ZoF-Snapshot-x64-67a75ee17-20190109.iso from https://pkg.trueos.org/iso/snapshot-zol/

To reproduce I downloaded the iso, created a 16GB image file, then ran:
>sudo bhyveload -m 1024M -d TrueOS-ZoF-Snapshot-x64-67a75ee17-20190109.iso vm0
>sudo bhyve -c 2 -m 1024M -H -A -P -g 0 -s 0,hostbridge -s 1,lpc -s 2,virtio-net,tap0 -s 3,virtio-blk,guest.img -s 31,ahci-cd,TrueOS-ZoF-Snapshot-x64-67a75ee17-20190109.iso -l com1,stdio vm0

Installed with all defaults, closed the vm, then saw the crash when I loaded the image with:

>sudo bhyveload -m 1024M -d guest.img vm0

**Comment by mattmacy** [comment]
You need a patched loader see: https://svnweb.freebsd.org/base?view=revision&revision=342747
