### ISSUE TITLE
Unable to create zpool due to drive being part of exported pool

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#71]
In the test pool_checkpoint/checkpoint_zhack_feat, 'zpool create' fails when specifying a vdev in an exported pool:
```
failed to find device md0, try specifying absolute path instead
failed to find device md1, try specifying absolute path instead
failed to find device md2, try specifying absolute path instead
invalid vdev specification use '-f' to override the following errors: /dev/md0 is part of exported pool 'testpool'
ERROR: zpool create -O sync=disabled testpool md0 exited 1
```

**Comment by kmoore134** [comment]
My guess is that the zpool label clear stuff isn't working here:

https://github.com/zfsonfreebsd/ZoF/blob/projects/zfsbsd/tests/zfs-tests/tests/functional/pool_checkpoint/checkpoint_zhack_feat.ksh#L46

This may be a legit but in the label clear functionality, something isn't getting cleaned up properly from the /dev/md* devices.

**Comment by kmoore134** [comment]
Disabled this test on FreeBSD:

https://github.com/zfsonfreebsd/ZoF/commit/6940cc4c476b029e145419bfe09306b46d8601e5
