### ISSUE TITLE
Fix or disable callbacks/zfs_mmp.ksh

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#73]
Currently zfs_mmp.ksh tries to read from sysfs and procfs. Not only would this need to be written anyway, it also looks for multihost_history, which is part of spa_stats.c that hasn't been added yet. This doesn't affect anything other than creating errors on most tests that fail for other reasons, since it tries to tack on history to the error log but fails.

**Comment by freqlabs** [comment]
Disabled mmp callbacks for now 167185264abc32cc44b047ddbcf99213eef6685c

**Comment by ghost** [comment]
This callback is disabled on FreeBSD.
