### ISSUE TITLE
Zinject '-e' flag fails in fault/auto_spare_002

### ISSUE THREAD

**Issue by ZackaryWelch** [zfsonfreebsd/ZoF#79]
Test fails running:
``zinject -d /tests/file-1 -e corrupt -f 50 -T read testpool``
with the error ``device error type must be 'io', 'nxio' or 'corrupt'``. Seems there is an issue reading the 'e' flag.

**Comment by mattmacy** [comment]
retry after 983bc7e88bfaccc3e7bf967018680f478a268819
