### ISSUE TITLE
zfs rename missing the -u flag

### ISSUE THREAD

**Issue by kmoore134** [zfsonfreebsd/ZoF#83]
FreeBSD's legacy ZFS has the -u flag in rename:

`         -u      Do not remount file systems during rename. If a file system's
                 mountpoint property is set to legacy or none, file system is
                 not unmounted even if this option is not given.
`

Not having this flag breaks beadm and probably other tools.

**Comment by mattmacy** [comment]
@kmoore134 please test after d74e2ac8c3907bb68edce3c57a5e08028613f8ac
