### ISSUE TITLE
zpool status not showing partition information

### ISSUE THREAD

**Issue by kmoore134** [zfsonfreebsd/ZoF#84]
On legacy ZFS, a zpool status will show "ada1p2" for the specific freebsd-zfs partition. ZoL is only showing the disk, which is incorrect since ada1p2 is the actual device in use. 
`
% sudo zpool status
  pool: tank
 state: ONLINE
status: Mismatch between pool hostid and system hostid on imported pool.
        This pool was previously imported into a system with a different hostid,
        and then was verbatim imported into this system.
action: Export this pool on all systems on which it is imported.
        Then import it to correct the mismatch.
   see: http://zfsonlinux.org/msg/ZFS-8000-EY
  scan: scrub repaired 0B in 0 days 00:43:14 with 0 errors on Fri Mar  8 22:48:19 2019
config:

        NAME        STATE     READ WRITE CKSUM
        tank        ONLINE       0     0     0
          ada1      ONLINE       0     0     0
`

`
% gpart show
=>        40  1048575920  ada1  GPT  (500G)
          40         512     1  freebsd-boot  (256K)
         552  1044469760     2  freebsd-zfs  (498G)
  1044470312     4096000     3  freebsd-swap  (2.0G)
  1048566312        9648        - free -  (4.7M)
`

**Comment by mattmacy** [comment]
@kmoore134 please check after f91bb6aa2ff3a7fcafa74b414d23cce7a647ced3
