### ISSUE TITLE
Incorrect error message from zpool command

### ISSUE THREAD

**Issue by ghost** [zfsonfreebsd/ZoF#90]
On FreeBSD, the message zpool prints when trying to create a pool without the zfs module loaded is incorrect. It should just load the module for the user, but it definitely shouldn't require `udevadm trigger`on FreeBSD.

```
root@freebsd12-zol:~ # zpool create tank foo
/dev/zfs and /proc/self/mounts are required.
Try running 'udevadm trigger' and 'mount -t proc proc /proc' as root.
root@freebsd12-zol:~ #
```

**Comment by allanjude** [comment]
This same error happens when you run 'zfs list' without zfs.ko loaded. Previously on FreeBSD this would automatically load zfs.ko
