### ISSUE TITLE
13-current unable to boot with sysutils/zol-kmod sysutils/zol

### ISSUE THREAD

**Issue by gldisater** [zfsonfreebsd/ZoF#92]
Rebuilt world and kernel with WITHOUT_ZFS=yes, installed sysutils/zol and zol-kmod and rebooted. Hangs after failing to mount / dataset with this snippet of kernel output:

can't handle raw ops yet!!!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
sysctl_warn_reuse: can't re-use a leaf (kstat.zfs.misc.dbufstats.cache_levels_bytes_N)!
can't handle raw ops yet!!!
ZFS filesystem version: 5
ZFS storage pool version: features support (5000)
can't handle raw ops yet!!!
usb_needs_explore_all: no devclass
Trying to mount root from zfs:zroot/ROOT/default []...
WARNING: WITNESS option enabled, expect reduced performance.
Mounting from zfs:zroot/ROOT/default failed with error 4; retrying for 3 more seconds

**Comment by mattmacy** [comment]
@gldisater Did you go through and delete all the existing zfs libraries and binaries from the install? Even if you got past mount root your system wouldn't work.

**Comment by debdrup** [comment]
I can reliably reproduce this by creating a brand new 1-CPU/2GB-memory/10GB-zvol-storage VM in bhyve on the freebsd-pkgbase images off the pkg.trueos.org servers, specifically the one named FreeBSD-HEAD-pkgbase-x64-20190515.iso from 15-May-2019 08:28.

See attached file bhyve.txt for full dmesg output.
[bhyve.txt](https://github.com/zfsonfreebsd/ZoF/files/3190933/bhyve.txt)

**Comment by kmoore134** [comment]
@mattmacy this is the same issue we're seeing on fresh install when ZoL is selected. No legacy ZFS libs exist on the box, just ZoL ones.

**Comment by kmoore134** [comment]
@freqlabs can you also assist in investigation this one?

**Comment by kmoore134** [comment]
Here's another repro case for the interested:

Grab ISO from:
http://pkg.trueos.org/iso/freebsd-pkgbase/

Install with "generic" flavor during installation, to ZFS on root, not UFS.

After install, run:

```
# pkg set --change-name os-generic-userland:os-zol-userland
# pkg set --change-name os-generic-userland-base:os-zol-userland-base
# pkg set --change-name os-generic-userland-docs:os-zol-userland-docs
# pkg set --change-name os-generic-kernel:os-zol-kernel
# pkg upgrade -f
```

This will change you from ZFS in base, to ZoL packages. After you reboot, ZoL will be loaded, and you will fail at mount-root as seen here.

**Comment by debdrup** [comment]
I've just installed FreeBSD-12-pkgbase-x64-20190516.iso from 16-May-2019 21:26 so it seems likely that it is that it's some change that has/had yet to be merged from head.

Are there older images to test with? If so, I think I can manage to do some legwork on narrowing down between which snapshots the issue snuck in.

**Comment by ghost** [comment]
After following the steps listed by @kmoore134 in https://github.com/zfsonfreebsd/ZoF/issues/92#issuecomment-493445780 I found that on the first reboot the system did fail at mountroot as described in the original report, but upon power cycling the machine the system booted normally with the updated packages.

**Comment by ghost** [comment]
On closer inspection, only the boot environment dataset mounted on /, but none of the other zfs filesystems mounted. I notice that there are no zfs related scripts in /etc/rc.d/

**Comment by kmoore134** [comment]
@freqlabs Ok, thats something I know where to fix, will take a look shortly.

**Comment by kmoore134** [comment]
Ok, the missing rc.d scripts should be fixed now:

https://github.com/trueos/trueos/commit/591ee5852ac9995cc27beeba4ac7f8a39de15c63

**Comment by kmoore134** [comment]
This is fixed in latest ZoL images. 

http://pkg.trueos.org/iso/freebsd12-pkgbase/
http://pkg.trueos.org/iso/freebsd-pkgbase/
