### ISSUE TITLE
ZOL prerolled images does not allow writing to tmp.

### ISSUE THREAD

**Issue by kusuriya** [zfsonfreebsd/ZoF#94]
### System information
Type | Version/Name
 ZOL image | FreeBSD 12 
Distribution Name: freebsd
Distribution Version: 12-zol

### Describe the problem you're observing
On the prerolled ZOL images for FreeBSD /tmp has an acl that makes it writable only as root

### Describe how to reproduce the problem
1. install from the provided FreeBSD-ZOL images on https://pkg.trueos.org/iso/freebsd12-zol/
2. create a non root user
3. `touch /tmp/test`
4. access denied 

I was able to verify this on a 3 machines including a VM from Conor Beh, one of Michael Dexter's thinkpad X230's and my own thinkpad T450p

**Comment by rqqb** [comment]
Correct. Fix by ‘chmod 1777 /tmp’ (as root)


--
Bob Bishop     from iPhone*
rb@gid.co.uk
+44 783 626 4518

**Comment by kusuriya** [comment]
chmoding didn't fix the issue for me, I had to do a setfacl and add rwx to group and other. it almost looks like an acl is set to keep tmp empty so someone can mount a tmpfs partition to it.

**Comment by kmoore134** [comment]
This appears fixed in the latest images here:

http://pkg.trueos.org/iso/freebsd-pkgbase/
http://pkg.trueos.org/iso/freebsd12-pkgbase/
