### ISSUE TITLE
Jail delegation feature is missing

### ISSUE THREAD

**Issue by allanjude** [zfsonfreebsd/ZoF#98]
### System information
FreeBSD stable/12 (ZoF CFT image 20190418)

### Describe the problem you're observing
ZFS on FreeBSD supports delegating a dataset to a jail. This allows root in the jail to control that dataset and all of its children. The 'jailed' property, when enabled, prevents the dataset from being mounted on the host system (global zone in solaris-speak used in ZFS code). Once a dataset is jailed, its mountpoint and other properties can be controlled by the administrator of the jail.

We make heavy use of this feature for containerizing customer workloads, and need it to exist after the ZoF transition.

### Describe how to reproduce the problem
```
# zfs set jailed=on testpool/delegated
cannot set property for 'testpool/delegated': invalid property 'jailed'
# zfs jail testjail testpool/delegated
unrecognized command 'jail'
```

**Comment by mattmacy** [comment]
@allanjude In upstream this property is called "zoned" and not "jailed" - Do we really need ifdefs to provide special naming for FreeBSD? This seems counter to the intent of openzfs.

**Comment by mattmacy** [comment]
The `zfs jail` command looks like a little copy pasta

**Comment by mattmacy** [comment]
please test  8ac10f2a131c4c32f419cd8e637bb82821167cef

**Comment by allanjude** [comment]
Confirmed that as of a67416d63ef3c6358df8e44aacc92cabe51f8838 the issue is fixed and delegation works as expected
